import os
import uuid
import logging
import traceback
import asyncio
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from database import AsyncSessionLocal
from models import Job, Video
from config import get_settings

from pipeline.script_gen import generate_script
from pipeline.manim_gen import render_manim_scene
from pipeline.tts_gen import generate_narration
from pipeline.subtitle_gen import generate_subtitles
from pipeline.video_assemble import assemble_scene, concatenate_scenes

logger = logging.getLogger(__name__)
settings = get_settings()

async def update_job_status(job_id: str, status: str, progress: float, error_message: str = None):
    """Helper function to update a job's progress in the database."""
    async with AsyncSessionLocal() as session:
        result = await session.execute(select(Job).filter(Job.id == job_id))
        job = result.scalar_one_or_none()
        if job:
            job.status = status
            job.progress = progress
            if error_message:
                job.error_message = error_message
            await session.commit()
            logger.info(f"Job {job_id} updated: status={status}, progress={progress}%")

async def run_pipeline(job_id: str, topic: str):
    """
    Main orchestration function running in the background.
    Manages state, updates DB, executes code blocks sequentially.
    """
    # Create directories
    job_dir = os.path.join(settings.output_dir, job_id)
    os.makedirs(job_dir, exist_ok=True)
    
    try:
        # Step 1: Generate Script
        await update_job_status(job_id, "GENERATING_SCRIPT", 10.0)
        script = await generate_script(topic)
        logger.info(f"Generated script structure: {script.get('title')}")
        
        scenes = script.get("scenes", [])
        if not scenes:
            raise ValueError("No scenes generated by the script LLM.")

        assembled_scenes = []
        total_scenes = len(scenes)

        # Process each scene
        for idx, scene in enumerate(scenes, 1):
            scene_id = f"scene_{idx}"
            scene_prefix = f"[Scene {idx}/{total_scenes}]"
            
            # Step 2: Render Manim code for this scene
            await update_job_status(job_id, f"RENDERING_ANIMATION (Scene {idx}/{total_scenes})", 20.0 + (idx - 1) / total_scenes * 60.0)
            manim_code = scene.get("manim_code", "")
            visual_path = await render_manim_scene(manim_code, scene_id, job_dir)
            
            # Step 3: Generate Voice Audio
            await update_job_status(job_id, f"GENERATING_AUDIO (Scene {idx}/{total_scenes})", 25.0 + (idx - 1) / total_scenes * 60.0)
            narration = scene.get("narration", "")
            audio_path = await generate_narration(narration, idx, job_dir)
            
            # Step 4: Transcribe / Sync Subtitles
            await update_job_status(job_id, f"GENERATING_SUBTITLES (Scene {idx}/{total_scenes})", 30.0 + (idx - 1) / total_scenes * 60.0)
            srt_path = await generate_subtitles(audio_path, narration, job_dir, idx)
            
            # Step 5: Assemble Video, Audio, and Subs into scene MP4
            await update_job_status(job_id, f"ASSEMBLING (Scene {idx}/{total_scenes})", 35.0 + (idx - 1) / total_scenes * 60.0)
            scene_output = os.path.join(job_dir, f"scene_{idx}_final.mp4")
            scene_assembled = await assemble_scene(visual_path, audio_path, srt_path, scene_output)
            
            assembled_scenes.append(scene_assembled)

        # Step 6: Concatenate all scene MP4s together
        await update_job_status(job_id, "CONCATENATING_SCENES", 90.0)
        final_video_path = os.path.join(settings.output_dir, f"{job_id}_final.mp4")
        await concatenate_scenes(assembled_scenes, final_video_path)

        # Step 7: Completed successfully! Save video metadata and update job status
        async with AsyncSessionLocal() as session:
            # Create a Video record
            video_id = str(uuid.uuid4())
            new_video = Video(
                id=video_id,
                job_id=job_id,
                title=script.get("title", f"Understanding {topic}"),
                file_path=os.path.basename(final_video_path),
                duration=None # Optional duration calculation
            )
            session.add(new_video)
            
            # Link job to video and update status
            result = await session.execute(select(Job).filter(Job.id == job_id))
            job = result.scalar_one_or_none()
            if job:
                job.status = "COMPLETED"
                job.progress = 100.0
                
            await session.commit()
            logger.info(f"Pipeline successfully completed for Job {job_id}!")

    except Exception as e:
        error_msg = f"Pipeline execution failed: {str(e)}"
        logger.error(error_msg)
        logger.error(traceback.format_exc())
        await update_job_status(job_id, "FAILED", 100.0, error_message=error_msg)
